<?php 
/* Creates a block */
function govhackhacks_block_info() {
  $blocks['datablock'] = array(
    'info' => t('Govhack Comparison data block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

function govhackhacks_block_view($delta = '') {
  $block = array();
  $currpage = url(NULL, array('absolute' => TRUE));
  switch($delta) {
    case 'datablock' :
      $block['title'] = '<none>';
      $block['content'] = govhackhacks_showresults();
      break;
  }
  return $block;
}

/* probably won't need this function but whatever, here it is anyway
   updates the other fields when a person is updated */
function govhackhacks_node_presave($node){
  $age = $node->field_age[LANGUAGE_NONE][0]['value'];
  if ($age >= 18 && $age <= 24) $node->field_age_range[LANGUAGE_NONE][0]['tid'] = 3;
  if ($age >= 25 && $age <= 34) $node->field_age_range[LANGUAGE_NONE][0]['tid'] = 4;
  if ($age >= 35 && $age <= 44) $node->field_age_range[LANGUAGE_NONE][0]['tid'] = 5;
  if ($age >= 45 && $age <= 54) $node->field_age_range[LANGUAGE_NONE][0]['tid'] = 6;
  if ($age >= 55 && $age <= 64) $node->field_age_range[LANGUAGE_NONE][0]['tid'] = 7;
  if ($age >= 65 && $age <= 74) $node->field_age_range[LANGUAGE_NONE][0]['tid'] = 8;
  if ($age >= 75 && $age <= 120) $node->field_age_range[LANGUAGE_NONE][0]['tid'] = 9;
}

/* Function that does all the actual stuff */
function govhackhacks_showresults(){
  $markup = '';
  $node = menu_get_object();
  $age = $node->field_age[LANGUAGE_NONE][0]['value'];
  $postcode = $node->field_postcode[LANGUAGE_NONE][0]['value'];
  if ($node->field_gender[LANGUAGE_NONE][0]['tid'] == 1) $gender = 'M'; // hardcoded TIDs
  if ($node->field_gender[LANGUAGE_NONE][0]['tid'] == 2) $gender = 'F';
  if ($node->field_indigenous[LANGUAGE_NONE][0]['value'] == 0) $indigenous = 'N';
  if ($node->field_indigenous[LANGUAGE_NONE][0]['value'] == 1) $indigenous = 'Y';
  // need to convert the postcode to LGA

  // wrap each set of results up in a div with a title
  //$age, $postcode, $gender, $indigenous;
  //----------- dummy data
  //    $lowagerange = 23;
   //   $indigenous = 'N';
    //  $postcode = 2015;
      //$gender = 'F';

  //-------------
  
  if ($age >=18 && $age <= 24) {
      $lowagerange = 18;
  } else if ( $age >=25 && $age <= 34){
      $lowagerange = 25;
  } else if ( $age >=35 && $age <= 44){
      $lowagerange = 35;
  } else if ( $age >=45 && $age <= 54){
      $lowagerange = 45;
  } else if ( $age >=55 && $age <= 64){
      $lowagerange = 55;
  } else if ( $age >=65 && $age <= 74){
      $lowagerange = 65;
  } else {
      // default;
      $lowagerange = 75;
  }

  $sql = "SELECT DISTINCT LifeExpectancy, CauseDeathOne, Overweight, NoJob, HighRiskDrinker,
                 AlcoholDrug, TroublePolice FROM showthegap_table
                 INNER JOIN showthegap_lgaTable ON
                 showthegap_lgaTable.Lga_Name = showthegap_table.LGA
                 WHERE AgeRangeLow =".$lowagerange. " AND Indigenous !='".$indigenous."' AND
                 PostcodeLga =" .$postcode. " AND Gender ='" .$gender."'";


  $db_host = 'localhost';
  $db_username = 'root';
  $db_pwd = 'root';
  $db_name = 'vanilladrupal';
  // Please replace this by using drupal in-built db fucction call.
  $con = mysql_connect($db_host,$db_username,$db_pwd);
  if (!$con) {
      die('Could not connect: ' . mysql_error());
  }
  mysql_select_db($db_name);

  $result = mysql_query($sql,$con);
  $answers = mysql_fetch_array($result);
  $final_answers = array();

  foreach($answers as $key => $value) {
      $final_answers[$key] = $value;
  }

  mysql_close($con);

  $markup .= '<div class="resultwrapper"><h2>How long have you got</h2>';
  $markup .= '<p>You\'re likely to live to the ripe old age of</p>';
  // content here

  $markup .= $final_answers['LifeExpectancy'];
  $markup .= '</div>';


  $markup .= '<div class="resultwrapper"><h2>Kicking the bucket</h2>';
  $markup .= '<p>What\'s likely to be your cause of death</p>';
  // content here
  $markup .= $final_answers['CauseDeathOne'];
  $markup .= '</div>';


  $markup .= '<div class="resultwrapper"><h2>Heavy news</h2>';
  $markup .= '<p>Are you likely to be obese?</p>';
  // content here
  $markup .= $final_answers['Overweight'];
  $markup .= '</div>';


  $markup .= '<div class="resultwrapper"><h2>Work, work, work</h2>';
  $markup .= '<p>Are you likely to be unemployed?</p>';
  // content here
  $markup .= $final_answers['NoJob'];
  $markup .= '</div>';


  $markup .= '<div class="resultwrapper"><h2>About that drink</h2>';
  $markup .= '<p>Are you at risk of being alcoholic?</p>';
  // content here
  $markup .= $final_answers['HighRiskDrinker'];
  $markup .= '</div>';


  $markup .= '<div class="resultwrapper"><h2>What\'s bad for you</h2>';
  $markup .= '<p>Are you likely to have drug or alcohol problems?</p>';
  // content here
  $markup .= $final_answers['AlcoholDrug'];
  $markup .= '</div>';


  $markup .= '<div class="resultwrapper"><h2>Stay out of trouble</h2>';
  $markup .= '<p>Are you likely to be in trouble with the police?</p>';
  // content here
  $markup .= $final_answers['TroublePolice'];
  $markup .= '</div>';


  return $markup;
}