<?php 
/* Creates a block */
function govhackhacks_block_info() {
  $blocks['datablock'] = array(
    'info' => t('Govhack Comparison data block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

function govhackhacks_block_view($delta = '') {
  $block = array();
  $currpage = url(NULL, array('absolute' => TRUE));
  switch($delta) {
    case 'datablock' :
      $block['title'] = '<none>';
      $block['content'] = govhackhacks_showresults();
      break;
  }
  return $block;
}

/* probably won't need this function but whatever, here it is anyway
   updates the other fields when a person is updated */
function govhackhacks_node_presave($node){
  $age = $node->field_age[LANGUAGE_NONE][0]['value'];
  if ($age >= 18 && $age <= 24) $node->field_age_range[LANGUAGE_NONE][0]['tid'] = 3;
  if ($age >= 25 && $age <= 34) $node->field_age_range[LANGUAGE_NONE][0]['tid'] = 4;
  if ($age >= 35 && $age <= 44) $node->field_age_range[LANGUAGE_NONE][0]['tid'] = 5;
  if ($age >= 45 && $age <= 54) $node->field_age_range[LANGUAGE_NONE][0]['tid'] = 6;
  if ($age >= 55 && $age <= 64) $node->field_age_range[LANGUAGE_NONE][0]['tid'] = 7;
  if ($age >= 65 && $age <= 74) $node->field_age_range[LANGUAGE_NONE][0]['tid'] = 8;
  if ($age >= 75 && $age <= 120) $node->field_age_range[LANGUAGE_NONE][0]['tid'] = 9;
}

/* Function that does all the actual stuff */
function govhackhacks_showresults(){
  $markup = '';
  $node = menu_get_object();
  $age = $node->field_age[LANGUAGE_NONE][0]['value'];
  $postcode = $node->field_postcode[LANGUAGE_NONE][0]['value'];
  if ($node->field_gender[LANGUAGE_NONE][0]['tid'] == 1) {$gender = 'M'; $gendertext = "male";}// hardcoded TIDs
  if ($node->field_gender[LANGUAGE_NONE][0]['tid'] == 2) {$gender = 'F'; $gendertext = "female";}
  if ($node->field_indigenous[LANGUAGE_NONE][0]['value'] == 0) $indigenous = 'N';
  if ($node->field_indigenous[LANGUAGE_NONE][0]['value'] == 1) $indigenous = 'Y';
  // need to convert the postcode to LGA

  // wrap each set of results up in a div with a title
  //$age, $postcode, $gender, $indigenous;
  //----------- dummy data
  //    $lowagerange = 23;
   //   $indigenous = 'N';
    //  $postcode = 2015;
      //$gender = 'F';

  //-------------
  
  if ($age >=18 && $age <= 24) {
      $lowagerange = 18;
  } else if ( $age >=25 && $age <= 34){
      $lowagerange = 25;
  } else if ( $age >=35 && $age <= 44){
      $lowagerange = 35;
  } else if ( $age >=45 && $age <= 54){
      $lowagerange = 45;
  } else if ( $age >=55 && $age <= 64){
      $lowagerange = 55;
  } else if ( $age >=65 && $age <= 74){
      $lowagerange = 65;
  } else {
      // default;
      $lowagerange = 75;
  }

  $sql = "SELECT DISTINCT {showthegap_table}.LifeExpectancy, {showthegap_table}.CauseDeathOne, {showthegap_table}.Overweight, {showthegap_table}.NoJob, {showthegap_table}.HighRiskDrinker,
                 {showthegap_table}.AlcoholDrug, {showthegap_table}.TroublePolice FROM {showthegap_table}
                 INNER JOIN {showthegap_lgaTable} ON
                 {showthegap_lgaTable}.Lga_Name = {showthegap_table}.LGA
                 WHERE (AgeRangeLow = :lowagerange AND Indigenous != :indigenous AND
                 PostcodeLga = :postcode AND Gender = :gender )";

  $your_sql = "SELECT DISTINCT {showthegap_table}.LifeExpectancy, {showthegap_table}.CauseDeathOne, {showthegap_table}.Overweight, {showthegap_table}.NoJob, {showthegap_table}.HighRiskDrinker,
                 {showthegap_table}.AlcoholDrug, {showthegap_table}.TroublePolice FROM {showthegap_table}
                 INNER JOIN {showthegap_lgaTable} ON
                 {showthegap_lgaTable}.Lga_Name = {showthegap_table}.LGA
                 WHERE (AgeRangeLow = :lowagerange AND Indigenous = :indigenous AND
                 PostcodeLga = :postcode AND Gender = :gender )";


  $answers = db_query($sql, array(':lowagerange'=>$lowagerange,':indigenous'=>$indigenous,':postcode'=>$postcode, ':gender'=>$gender));
  $your_answers = db_query($your_sql, array(':lowagerange'=>$lowagerange,':indigenous'=>$indigenous,':postcode'=>$postcode, ':gender'=>$gender));

  $final_answers = $answers->fetchObject();
  $your_final_answers = $your_answers->fetchObject();
  if ($gender === 'M') {
       $opposite = 'him';
       $else = 'He';
   } else {
       $opposite = 'her';
       $else = 'She';
   }

  if ((!isset($your_final_answers->LifeExpectancy)) || (!isset($final_answers->LifeExpectancy))) {
      // The Postcode does not exist then sorry for this quick and dirty hacky (yet temporary) solution.
      // Will remove this solution and handle the errors properly in drupal way asap as I feel dirty right now :(.
      header('Location:  http://showthegap.org');
  }

  $markup .= "<h1>As a $age year old $gendertext in $postcode</h1>";

  $markup .= '<div class="resultwrapper"><h2>How long have you got</h2>';

  $ages = round($your_final_answers->LifeExpectancy) - round($final_answers->LifeExpectancy);
  if ($ages < 0) $diffword = " less ";
  else $diffword = " more ";
  $agediff = abs($ages);


  $markup .= "<p>You will live <span class=\"thegap\">$agediff</span> $diffword years than $opposite.</p>";
  $markup .= '<span class="answeryou">'.round($your_final_answers->LifeExpectancy) . " years</span>";
  $markup .= '<span class="answerthem">'.round($final_answers->LifeExpectancy) . " years</span>";
  $markup .= '</div>';

  $markup .= '<div class="resultwrapper"><h2>Kicking the bucket</h2>';
  $markup .= '<p>What\'s the leading cause of death for your age?</p>';
  // content here
  $markup .= '<span class="answeryou">you: '.$your_final_answers->CauseDeathOne . "</span>";
  $markup .= '<span class="answerthem">'."$opposite: ". $final_answers->CauseDeathOne. "</span>";
  $markup .= '</div>';

  $markup .= '<div class="resultwrapper"><h2>Heavy news</h2>';
  $markup .= '<p>What are your chances of being obese?</p>';
  // content here

       $times = $final_answers->Overweight/$your_final_answers->Overweight;
       $number_times = round($times,1);
       if (abs($number_times) > 2) {
           //$markup .= "$else is $number_times times more likely to be obese than you </br>";
       } else {
           //$markup .= "You two are almost the same </br>";
       }

  $markup .= '<span class="answeryou">you: '.$your_final_answers->Overweight . "%</span>";
  $markup .= '<span class="answerthem">'."$opposite: ". $final_answers->Overweight . "%</span>";
  $markup .= '</div>';


  $markup .= '<div class="resultwrapper"><h2>Work, work, work</h2>';
  //$markup .= '<p>Are you likely to be unemployed?</p>';
  // content here

  $unemployed_times = $final_answers->NoJob/$your_final_answers->NoJob;
  $unemployed_number_times = round($unemployed_times,1);
  $indi_unemployed_times = $your_final_answers->NoJob/$final_answers->NoJob;
  $indi_unemployed_number_times = round($indi_unemployed_times,1);
      if ((abs($unemployed_number_times) > 2) && ($indigenous === 'N')) {
          $markup .= "<p>$else is <span class=\"thegap\">$unemployed_number_times x</span> more likely to be unemployed than you.</p>";
      } else if ((abs($indi_unemployed_number_times) > 2) && ($indigenous === 'Y')){
          $markup .= "<p> You are <span class=\"thegap\">$indi_unemployed_number_times x</span> more likely to be unemployed than $opposite. </p>";
      } else {
          $markup .= "<p>You have similar chances of being unemployed.</p>";
      }
  $markup .= '<span class="answeryou">you: '.$your_final_answers->NoJob . "%</span>";
  $markup .= '<span class="answerthem">'."$opposite: ". $final_answers->NoJob ."%</span>";
  $markup .= '</div>';


  $markup .= '<div class="resultwrapper"><h2>About that drink</h2>';
  //$markup .= '<p>Are you at risk of being alcoholic?</p>';
  // content here

   $HighRiskDrinker_times = $final_answers->HighRiskDrinker/$your_final_answers->HighRiskDrinker;
   $HighRiskDrinker_number_times = round($HighRiskDrinker_times,1);
   $indi_HighRiskDrinker_times = $your_final_answers->HighRiskDrinker/$final_answers->HighRiskDrinker;
   $indi_HighRiskDrinker_number_times = round($indi_HighRiskDrinker_times,1);
      if ((abs($HighRiskDrinker_number_times) > 2) && ($indigenous === 'N')) {
          $markup .= "<p>$else is <span class=\"thegap\">$HighRiskDrinker_number_times x</span> more likely to be at risk of being alcoholic than you.</p>";
      } else if ((abs($indi_HighRiskDrinker_number_times) > 2) && ($indigenous === 'Y')) {
          $markup .= "<p> You are <span class=\"thegap\">$indi_HighRiskDrinker_number_times x</span> more likely to be at risk of being alcoholic than $opposite. </p>";
      } else {
          $markup .= "<p>You have a similar risk of being alcoholic.</p>";
      }
  $markup .= '<span class="answeryou">you: '.$your_final_answers->HighRiskDrinker . "%</span>";
  $markup .= '<span class="answerthem">'."$opposite: ".$final_answers->HighRiskDrinker ."%</span>";
  $markup .= '</div>';


  $markup .= '<div class="resultwrapper"><h2>What\'s bad for you</h2>';
  //$markup .= '<p>Are you likely to have drug or alcohol problems?</p>';
  // content here

  $AlcoholDrug_times = $final_answers->AlcoholDrug/$your_final_answers->AlcoholDrug;
  $AlcoholDrug_number_times = round($AlcoholDrug_times,1);
  $indi_AlcoholDrug_times = $your_final_answers->AlcoholDrug/$final_answers->AlcoholDrug;
  $indi_AlcoholDrug_number_times = round($indi_AlcoholDrug_times,1);
      if ((abs($AlcoholDrug_number_times) > 2) && ($indigenous === 'N')) {
          $markup .= "<p>$else is <span class=\"thegap\">$AlcoholDrug_number_times x</span> more likely to have drug or alcohol problems than you.</p>";
      } else if ((abs($indi_AlcoholDrug_number_times) > 2) && ($indigenous === 'Y')) {
          $markup .= "<p> You are <span class=\"thegap\">$indi_AlcoholDrug_number_times x</span> more likely to have drug or alcohol problems than $opposite. </p>";
      } else {
          $markup .= "<p>You have a similar risk of having drug or alcohol problems.</p>";
      }
  $markup .= '<span class="answeryou">you: '.$your_final_answers->AlcoholDrug . "%</span>";
  $markup .= '<span class="answerthem">'."$opposite: ".$final_answers->AlcoholDrug. "%</span>";
  $markup .= '</div>';


  $markup .= '<div class="resultwrapper"><h2>Stay out of trouble</h2>';
  //$markup .= '<p>Are you likely to be in trouble with the police?</p>';
  // content here
  $TroublePolice_times = $final_answers->TroublePolice/$your_final_answers->TroublePolice;
  $TroublePolice_number_times = round($TroublePolice_times,1);
  $indi_TroublePolice_times = $your_final_answers->TroublePolice/$final_answers->TroublePolice;
  $indi_TroublePolice_number_times = round($indi_TroublePolice_times,1);
      if ((abs($TroublePolice_number_times)) > 2 && ($indigenous === 'N')) {
          $markup .= "<p>$else is <span class=\"thegap\">$TroublePolice_number_times x</span> more likely to be in trouble with the police than you.</p>";
      } else if ((abs($indi_TroublePolice_number_times)) > 2 && ($indigenous === 'Y')) {
          $markup .= "<p> You are <span class=\"thegap\">$indi_TroublePolice_number_times x</span> more likely to be in trouble with the police than $opposite. </p>";
      } else {
          $markup .= "<p>You have similar chances of being in trouble with the police.</p>";
      }
  $markup .= '<span class="answeryou">you: '.$your_final_answers->TroublePolice . "%</span>";
  $markup .= '<span class="answerthem">'."$opposite: ".$final_answers->TroublePolice. "%</span>";
  $markup .= '</div>';

$markup .= 
"<p>Now you know.  But now what, you ask?
You’ve taken the first step in making a difference – you’ve put yourself in the picture.
If more people know how big the Gap is, more people can get behind the efforts to close it.
</p><p>
Come back and recheck your Gap now and then. See what the data says, whether it is actually closing over time.
</p><p>
As we get more access to data, we can show you the progress over time. Whether it is local initiatives,  community action, where the government is putting its money, and HOW SUCCESSFUL those initiatives are, we now know what to keep an eye out for.
</p><p>
And now, so do you.
</p>";

  return $markup;
}